-- Initialize mock Oracle DB #1 with five comparable tables and seed data
-- Tables are created in SYSTEM schema so that application (connecting as SYSTEM)
-- can query them without schema qualification.

-- Ensure we operate under SYSTEM schema (script is executed by the base image in the PDB context)
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = SYSTEM';
END;
/

-- Helper to drop table if it exists
CREATE OR REPLACE PROCEDURE drop_table_if_exists(p_owner VARCHAR2, p_table VARCHAR2) AS
  v_cnt INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
  FROM all_tables
  WHERE owner = UPPER(p_owner) AND table_name = UPPER(p_table);
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_owner || '.' || p_table || ' PURGE';
  END IF;
END;
/

BEGIN drop_table_if_exists('SYSTEM', 'CUSTOMERS'); END;
/
BEGIN drop_table_if_exists('SYSTEM', 'PRODUCTS'); END;
/
BEGIN drop_table_if_exists('SYSTEM', 'ORDERS'); END;
/
BEGIN drop_table_if_exists('SYSTEM', 'EMPLOYEES'); END;
/
BEGIN drop_table_if_exists('SYSTEM', 'DEPARTMENTS'); END;
/

-- CUSTOMERS
CREATE TABLE SYSTEM.CUSTOMERS (
  ID        NUMBER       PRIMARY KEY,
  NAME      VARCHAR2(100) NOT NULL,
  EMAIL     VARCHAR2(150),
  CREATED_AT DATE DEFAULT SYSDATE
);

-- PRODUCTS
CREATE TABLE SYSTEM.PRODUCTS (
  ID        NUMBER        PRIMARY KEY,
  NAME      VARCHAR2(100) NOT NULL,
  PRICE     NUMBER(10,2)  NOT NULL,
  ACTIVE    CHAR(1)       DEFAULT 'Y' CHECK (ACTIVE IN ('Y','N'))
);

-- ORDERS
CREATE TABLE SYSTEM.ORDERS (
  ID          NUMBER        PRIMARY KEY,
  CUSTOMER_ID NUMBER        NOT NULL,
  PRODUCT_ID  NUMBER        NOT NULL,
  QTY         NUMBER        NOT NULL,
  ORDER_DATE  DATE          NOT NULL,
  STATUS      VARCHAR2(20)  NOT NULL,
  CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES SYSTEM.CUSTOMERS(ID),
  CONSTRAINT FK_ORDERS_PRODUCT  FOREIGN KEY (PRODUCT_ID)  REFERENCES SYSTEM.PRODUCTS(ID)
);

-- EMPLOYEES
CREATE TABLE SYSTEM.EMPLOYEES (
  ID         NUMBER         PRIMARY KEY,
  FIRST_NAME VARCHAR2(50)   NOT NULL,
  LAST_NAME  VARCHAR2(50)   NOT NULL,
  DEPT_ID    NUMBER,
  HIRED_AT   DATE
);

-- DEPARTMENTS
CREATE TABLE SYSTEM.DEPARTMENTS (
  ID     NUMBER        PRIMARY KEY,
  NAME   VARCHAR2(100) NOT NULL,
  REGION VARCHAR2(50)
);

-- Seed data for DB1 (baseline)
INSERT INTO SYSTEM.DEPARTMENTS (ID, NAME, REGION) VALUES (10, 'Engineering', 'EU');
INSERT INTO SYSTEM.DEPARTMENTS (ID, NAME, REGION) VALUES (20, 'Sales', 'NA');
INSERT INTO SYSTEM.DEPARTMENTS (ID, NAME, REGION) VALUES (30, 'HR', 'EU');

INSERT INTO SYSTEM.EMPLOYEES (ID, FIRST_NAME, LAST_NAME, DEPT_ID, HIRED_AT) VALUES (1, 'Alice', 'Smith', 10, DATE '2020-01-10');
INSERT INTO SYSTEM.EMPLOYEES (ID, FIRST_NAME, LAST_NAME, DEPT_ID, HIRED_AT) VALUES (2, 'Bob',   'Johnson', 20, DATE '2019-05-03');
INSERT INTO SYSTEM.EMPLOYEES (ID, FIRST_NAME, LAST_NAME, DEPT_ID, HIRED_AT) VALUES (3, 'Carol', 'Lee', 30, DATE '2021-07-21');

INSERT INTO SYSTEM.CUSTOMERS (ID, NAME, EMAIL, CREATED_AT) VALUES (1, 'Contoso Ltd', 'contact@contoso.com', DATE '2022-01-01');
INSERT INTO SYSTEM.CUSTOMERS (ID, NAME, EMAIL, CREATED_AT) VALUES (2, 'Fabrikam Inc', 'info@fabrikam.com', DATE '2022-02-02');
INSERT INTO SYSTEM.CUSTOMERS (ID, NAME, EMAIL, CREATED_AT) VALUES (3, 'Northwind', 'hello@northwind.com', DATE '2022-03-03');

INSERT INTO SYSTEM.PRODUCTS (ID, NAME, PRICE, ACTIVE) VALUES (100, 'Widget', 9.99, 'Y');
INSERT INTO SYSTEM.PRODUCTS (ID, NAME, PRICE, ACTIVE) VALUES (101, 'Gadget', 19.99, 'Y');
INSERT INTO SYSTEM.PRODUCTS (ID, NAME, PRICE, ACTIVE) VALUES (102, 'Doohickey', 4.50, 'N');

INSERT INTO SYSTEM.ORDERS (ID, CUSTOMER_ID, PRODUCT_ID, QTY, ORDER_DATE, STATUS) VALUES (1000, 1, 100, 3, DATE '2023-01-15', 'OPEN');
INSERT INTO SYSTEM.ORDERS (ID, CUSTOMER_ID, PRODUCT_ID, QTY, ORDER_DATE, STATUS) VALUES (1001, 2, 101, 1, DATE '2023-02-20', 'SHIPPED');
INSERT INTO SYSTEM.ORDERS (ID, CUSTOMER_ID, PRODUCT_ID, QTY, ORDER_DATE, STATUS) VALUES (1002, 3, 102, 10, DATE '2023-03-30', 'CANCELLED');

COMMIT;
